language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
matrix:
  include:
    # These are the latest Go versions.
    - os: linux
      dist: trusty
      sudo: required
      go: 1.11.x
      script:
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go install
        - travis_wait 60 go run build/ci.go test
      before_deploy:
        - sh build/deploy.sh
      deploy:
        provider: releases
        api_key:
          secure: "Sp41JF8t0+hixcgCxbv32TA5Yz/COE4Tax06ZRiKN0MQ7yF4unYmF0VPIoZV2SePM5U6oXn935NhiOsniYIbhX8tkXLFt7ksnsubcslX0a77tBMXfCVQtg+Ldrl9FxxMnskQxZl2kklUzGSdJw8PfHdgVXhkmr8dlOzNDnahiIwDvWePMHBG65IDsrqNtBij8bQfvMAR9lM0gE7zLKZsQrnopz6N/P5gz+WqcFk2acTIOJSW8Hmd0IVNKpXwO15KfM9Ip3xLJZCYA+2SGD3vLRGELKZYI0j2qkhvSvTy3/QVcmgovW2mWOgTjtb3NjjQOrFpK7VgionpNYo1/Itwhqs12BYLEyvRIk14C3U2rE/5CfnMwEUxmHDQmt/O1h1VROdLQdD4UATSy4vMZK0kQGIgMkyNjTjsBYpmoKJ2KsdxfG4Ay6IQlN4CI909z9fEBoC4ZWdx1ppUcd+VH+4Rw8x8jxOdkkuCjAvrGf4NGiI3zZ0q05FYlKag/LV+M0ZogRU393hFQaLZJPXaX5IXK8IrTrbjo4n2pU7BISYRjcmCK1jfcfO3/DoBkojNIkj50HlX520TJlUjIv/L2Tncx5M9CI1WV4fSVF0Djqg2eXheFV9aEu7omdYs63o+OAt/Ly/Y57AR/6/J/qc9s+R09UgQUCmLoA093IId19jS27Y="
        file: multi-geth*-$TRAVIS_OS_NAME.*
        file_glob: true
        draft: true
        name: "rr-$TRAVIS_COMMIT"
        body: "Independent multi-geth release by Rotblauer, forked from https://github.com/ethoxy/multi-geth/releases. The commit SHA will not match any existing commit in the master branch because this is not the project's canonical repo or branch. This is just an independent release for purposes of redundancy and demonstration. You can, however, use the SHA256 hashes of each binary for reference, provided in the `-sha256s.txt` file."
        on:
          branch: rotblauer-release
        skip_cleanup: true
        tag_name: "rr-$TRAVIS_COMMIT"

    - os: osx
      go: 1.11.x
      script:
        - echo "Increase the maximum number of open file descriptors on macOS"
        - NOFILE=20480
        - sudo sysctl -w kern.maxfiles=$NOFILE
        - sudo sysctl -w kern.maxfilesperproc=$NOFILE
        - sudo launchctl limit maxfiles $NOFILE $NOFILE
        - sudo launchctl limit maxfiles
        - ulimit -S -n $NOFILE
        - ulimit -n
        - unset -f cd # workaround for https://github.com/travis-ci/travis-ci/issues/8703
        - go run build/ci.go install
      before_deploy:
        - sh build/deploy.sh
      deploy:
        provider: releases
        api_key:
          secure: "Sp41JF8t0+hixcgCxbv32TA5Yz/COE4Tax06ZRiKN0MQ7yF4unYmF0VPIoZV2SePM5U6oXn935NhiOsniYIbhX8tkXLFt7ksnsubcslX0a77tBMXfCVQtg+Ldrl9FxxMnskQxZl2kklUzGSdJw8PfHdgVXhkmr8dlOzNDnahiIwDvWePMHBG65IDsrqNtBij8bQfvMAR9lM0gE7zLKZsQrnopz6N/P5gz+WqcFk2acTIOJSW8Hmd0IVNKpXwO15KfM9Ip3xLJZCYA+2SGD3vLRGELKZYI0j2qkhvSvTy3/QVcmgovW2mWOgTjtb3NjjQOrFpK7VgionpNYo1/Itwhqs12BYLEyvRIk14C3U2rE/5CfnMwEUxmHDQmt/O1h1VROdLQdD4UATSy4vMZK0kQGIgMkyNjTjsBYpmoKJ2KsdxfG4Ay6IQlN4CI909z9fEBoC4ZWdx1ppUcd+VH+4Rw8x8jxOdkkuCjAvrGf4NGiI3zZ0q05FYlKag/LV+M0ZogRU393hFQaLZJPXaX5IXK8IrTrbjo4n2pU7BISYRjcmCK1jfcfO3/DoBkojNIkj50HlX520TJlUjIv/L2Tncx5M9CI1WV4fSVF0Djqg2eXheFV9aEu7omdYs63o+OAt/Ly/Y57AR/6/J/qc9s+R09UgQUCmLoA093IId19jS27Y="
        file: multi-geth*-$TRAVIS_OS_NAME.*
        file_glob: true
        draft: true
        name: "rr-$TRAVIS_COMMIT"
        body: "Independent multi-geth release by Rotblauer, forked from https://github.com/ethoxy/multi-geth/releases. The commit SHA will not match any existing commit in the master branch because this is not the project's canonical repo or branch. This is just an independent release for purposes of redundancy and demonstration. You can, however, use the SHA256 hashes of each binary for reference, provided in the `-sha256s.txt` file."
        on:
          branch: rotblauer-release
        skip_cleanup: true
        tag_name: "rr-$TRAVIS_COMMIT"

    # This builder only tests code linters on latest version of Go
    - os: linux
      dist: trusty
      go: 1.11.x
      env:
        - lint
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - go run build/ci.go lint
