language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
matrix:
  include:
    # These are the latest Go versions.
    - os: linux
      dist: trusty
      sudo: required
      go: 1.11.x
      script:
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go install
        - travis_wait 60 go run build/ci.go test
      before_deploy:
        - sh build/deploy.sh
      deploy:
        provider: releases
        api_key:
          secure: rYGs0E3OZoN/TYrMf0NVslpQrFhkrccqpZBt3nEjE/gBuBbSvkhn4VDC/s019U7MFnhMsDik52bL/mnjlNt0E8oIV1bdF72BWKxymhtkzlN57h6Q/VZAzJMnhn4EYe8pgjp19CXzh0L7AEFc7IJVL5E679UmFdrT0ERW2ifLuU9PX6K0S2uoccc9oXosnThptkHBSn4oHLtS0LFMHVyKy57yfQ79OAI6bov5pkiKsqjnUpm+HEVNbpyLe48yBQHdCyly1GGPClh3/xGya7YgY/kErLEwO0WyASgysDHkz3bC26kdVocURHbf2RYCQtR5nRoRqeAk8kGin7q+K/Oi2qgLx/3mb7MgQZAYTDRJZfpOaN98rlVJMFwK2yZZA/FvuWTCNX6bZCVpd1vmyN8Xm55GzFEo7OgRFN411AQ7apcjJsRVTrOWk/GHp74djFmQP6t4pGeBczdnRfGvOrACS3TgY6sYFKG1NJkCDT4hLQKXgXwuXTKM406XcZjbB3Ussw10fRoLUyzHzsbBv+VHoVCEm9k9ozv3podZnLqePkjmxI6KW88VYqobGRigxCkyHJELhZiiTZGUirGrCzGa5sxtet9Tkt/RA9I2KsezHr5EGfgNug/lJi/fm/o43ehbNP3laMPrl+mla8PQ9BuzyDq7hknhcwyN9EWkXgDguJU=
        file: multi-geth*-$TRAVIS_OS_NAME.*
        file_glob: true
        draft: true
        name: "$TRAVIS_TAG.$TRAVIS_COMMIT"
        body: "Independent multi-geth release by Rotblauer, forked from https://github.com/ethoxy/multi-geth/releases."
        on:
          branch: rotblauer-release
        skip_cleanup: true
        tag_name: "rr-$TRAVIS_TAG.$TRAVIS_COMMIT"

    - os: osx
      go: 1.11.x
      script:
        - echo "Increase the maximum number of open file descriptors on macOS"
        - NOFILE=20480
        - sudo sysctl -w kern.maxfiles=$NOFILE
        - sudo sysctl -w kern.maxfilesperproc=$NOFILE
        - sudo launchctl limit maxfiles $NOFILE $NOFILE
        - sudo launchctl limit maxfiles
        - ulimit -S -n $NOFILE
        - ulimit -n
        - unset -f cd # workaround for https://github.com/travis-ci/travis-ci/issues/8703
        - go run build/ci.go install
      before_deploy:
        - sh build/deploy.sh
      deploy:
        provider: releases
        api_key:
          secure: rYGs0E3OZoN/TYrMf0NVslpQrFhkrccqpZBt3nEjE/gBuBbSvkhn4VDC/s019U7MFnhMsDik52bL/mnjlNt0E8oIV1bdF72BWKxymhtkzlN57h6Q/VZAzJMnhn4EYe8pgjp19CXzh0L7AEFc7IJVL5E679UmFdrT0ERW2ifLuU9PX6K0S2uoccc9oXosnThptkHBSn4oHLtS0LFMHVyKy57yfQ79OAI6bov5pkiKsqjnUpm+HEVNbpyLe48yBQHdCyly1GGPClh3/xGya7YgY/kErLEwO0WyASgysDHkz3bC26kdVocURHbf2RYCQtR5nRoRqeAk8kGin7q+K/Oi2qgLx/3mb7MgQZAYTDRJZfpOaN98rlVJMFwK2yZZA/FvuWTCNX6bZCVpd1vmyN8Xm55GzFEo7OgRFN411AQ7apcjJsRVTrOWk/GHp74djFmQP6t4pGeBczdnRfGvOrACS3TgY6sYFKG1NJkCDT4hLQKXgXwuXTKM406XcZjbB3Ussw10fRoLUyzHzsbBv+VHoVCEm9k9ozv3podZnLqePkjmxI6KW88VYqobGRigxCkyHJELhZiiTZGUirGrCzGa5sxtet9Tkt/RA9I2KsezHr5EGfgNug/lJi/fm/o43ehbNP3laMPrl+mla8PQ9BuzyDq7hknhcwyN9EWkXgDguJU=
        file: multi-geth*-$TRAVIS_OS_NAME.*
        file_glob: true
        draft: true
        name: "$TRAVIS_TAG.$TRAVIS_COMMIT"
        body: "Independent multi-geth release by Rotblauer, forked from https://github.com/ethoxy/multi-geth/releases."
        on:
          branch: rotblauer-release
        skip_cleanup: true
        tag_name: "rr-$TRAVIS_TAG.$TRAVIS_COMMIT"

    # This builder only tests code linters on latest version of Go
    - os: linux
      dist: trusty
      go: 1.11.x
      env:
        - lint
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - go run build/ci.go lint
